### ISSUE TITLE
Using maxRetries

### ISSUE THREAD

**Issue by ghost** [lucianotonet/groq-php#2]
Obrigado por desenvolver esta biblioteca.

Eu queria saber como a biblioteca funciona com o middleware retry do Guzzle.

A documentação diz que podemos usar a opção `maxRetries` para definir o número de tentativas. No entanto, eu não vejo `maxRetries` como uma opção de requisição válida para o Guzzle: https://docs.guzzlephp.org/en/stable/request-options.html

Eu não estou entendendo como as tentativas devem funcionar ao construir o objeto Request do Guzzle. Esta é uma funcionalidade que ainda não foi implementada?

**Comment by lucianotonet** [comment]
@spectrumvoip-stefano De fato, essa opção não parece ser válida. Usei os outros pacotes oficiais do Groq como base para desenvolver este, mas não tenho certeza se essa opção é realmente respeitada nos servidores do Groq. Removi a referência do readme para evitar confusão.

Obrigado pela observação.
