### ISSUE TITLE
Support Groq Audio ?

### ISSUE THREAD

**Issue by flemzord** [lucianotonet/groq-php#5]
Hello, 

I think it would be interesting to manage in the Groq SDK & Laravel facade the support of the Audio part (Transcription & Translate). 
What do you think? 

https://console.groq.com/docs/speech-text

**Comment by lucianotonet** [comment]
Hi @flemzord 
Added support to audio transcription and translation on [v0.0.6](https://github.com/lucianotonet/groq-php/releases/tag/v0.0.6).
Added some basic examples on Readme file. Also, some working examples was added [here](https://github.com/lucianotonet/groq-php/blob/main/examples/audio-translations.php) and [here](https://github.com/lucianotonet/groq-php/blob/main/examples/audio-transcriptions.php)

Could you please test it and provide some feedback?
