### ISSUE TITLE
missing $apiKey

### ISSUE THREAD

**Issue by zachary** [lucianotonet/groq-php#7]
I setup both export GROQ_API_KEY=xxx and .env file, however 
Uncaught TypeError: Cannot assign null to property LucianoTonet\GroqPHP\Groq::$apiKey of type string in 

Please help, thanks

**Comment by lucianotonet** [comment]
Hi @zachary 

Try passing your api key manually on the client initialization like this:

```php
use LucianoTonet\GroqPHP\Groq;

$groq = new Groq( "YOUR_API_KEY_HERE" );
```

Just for check it out. Try it and let me know.

**Comment by zachary** [comment]
Thank you for letting me know, I just noticed the issue comes from phpdotenv.
